[tool.poetry]
name = "logbt"
version = "0.4.0"
description = ""
authors = ["SmsS4 <smss.lite@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.5"
loguru = "^0.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
